/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *image15;
  GtkWidget *button15nbetud;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (acceuil, 1000, 800);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (acceuil), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 808, 688);
  gtk_widget_set_size_request (button1, 136, 61);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  image15 = create_pixmap (acceuil, "262311130_1122108558323408_8330249642595730814_n.jpg");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed1), image15, -32, 24);
  gtk_widget_set_size_request (image15, 1056, 296);

  button15nbetud = gtk_button_new_with_mnemonic (_("Nombre d'etudiant de chaque niveau"));
  gtk_widget_show (button15nbetud);
  gtk_fixed_put (GTK_FIXED (fixed1), button15nbetud, 352, 488);
  gtk_widget_set_size_request (button15nbetud, 300, 70);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 376, 352);
  gtk_widget_set_size_request (button2, 208, 62);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Gestion Etudiant"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button15nbetud, "clicked",
                    G_CALLBACK (on_button15nbetud_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_AcceuilGestion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");
  GLADE_HOOKUP_OBJECT (acceuil, image15, "image15");
  GLADE_HOOKUP_OBJECT (acceuil, button15nbetud, "button15nbetud");
  GLADE_HOOKUP_OBJECT (acceuil, button2, "button2");
  GLADE_HOOKUP_OBJECT (acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (acceuil, label2, "label2");

  return acceuil;
}

GtkWidget*
create_gestion (void)
{
  GtkWidget *gestion;
  GtkWidget *fixed2;
  GtkWidget *button14quitaz;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label238;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *calendar1;
  GtkWidget *button13;
  GtkWidget *image12;
  GtkWidget *button12_azz;
  GtkWidget *image13;
  GtkWidget *image17;
  GtkWidget *label12;
  GtkWidget *label5;
  GtkWidget *label4;
  GtkWidget *label6;
  GtkWidget *label13;
  GtkWidget *label3;
  GtkWidget *sexeaz;
  GtkWidget *label8;
  GtkWidget *comboboxaz;
  GtkWidget *label11;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *label35;
  GtkWidget *label34;
  GtkWidget *label10;
  GtkWidget *label235;
  GtkWidget *button14;
  GtkWidget *labelsexe;
  GtkWidget *label9;
  GtkWidget *label7;
  GtkWidget *label236;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *OkAZ;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton1;
  GtkWidget *label234;
  GtkWidget *label15;
  GtkWidget *fixed4;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label16;
  GtkWidget *label36;
  GtkWidget *label20;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label21;
  GtkWidget *image16;
  GtkWidget *label37;
  GtkWidget *label239;
  GtkWidget *entrySexe;
  GtkWidget *labelSexe;
  GtkWidget *label22;
  GtkWidget *fixed5;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview2;
  GtkWidget *entry10;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label30;
  GtkWidget *label29;
  GtkWidget *label26;
  GtkWidget *label31;
  GtkWidget *fixed7;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label42;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeview3;
  GtkWidget *label44;
  GtkWidget *button11;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label46;
  GtkWidget *label45;
  GtkWidget *label43;
  GtkWidget *label38;

  gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion, 1000, 800);
  gtk_window_set_title (GTK_WINDOW (gestion), _("gestion Foyer"));
  gtk_window_set_position (GTK_WINDOW (gestion), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion), fixed2);

  button14quitaz = gtk_button_new ();
  gtk_widget_show (button14quitaz);
  gtk_fixed_put (GTK_FIXED (fixed2), button14quitaz, 776, 16);
  gtk_widget_set_size_request (button14quitaz, 74, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button14quitaz), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label238 = gtk_label_new_with_mnemonic (_("Quit"));
  gtk_widget_show (label238);
  gtk_box_pack_start (GTK_BOX (hbox12), label238, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 40);
  gtk_widget_set_size_request (notebook1, 1000, 768);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 152, 168);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 416, 168);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 416, 240);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 152, 240);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 152, 112);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1, 728, 24);
  gtk_widget_set_size_request (calendar1, 162, 186);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed3), button13, 720, 280);
  gtk_widget_set_size_request (button13, 80, 48);

  image12 = create_pixmap (gestion, "button-facebookfinal.svg");
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button13), image12);

  button12_azz = gtk_button_new ();
  gtk_widget_show (button12_azz);
  gtk_fixed_put (GTK_FIXED (fixed3), button12_azz, 816, 280);
  gtk_widget_set_size_request (button12_azz, 78, 48);

  image13 = create_pixmap (gestion, "aaaaaaaaaaa.png");
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (button12_azz), image13);

  image17 = create_pixmap (gestion, "foyerrrr.jpeg");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed3), image17, 704, 360);
  gtk_widget_set_size_request (image17, 221, 189);

  label12 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 64, 104);
  gtk_widget_set_size_request (label12, 104, 48);

  label5 = gtk_label_new (_("Prenom : "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 312, 160);
  gtk_widget_set_size_request (label5, 104, 48);

  label4 = gtk_label_new (_("Adresse : "));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 48, 232);
  gtk_widget_set_size_request (label4, 104, 48);

  label6 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 48, 160);
  gtk_widget_set_size_request (label6, 104, 48);

  label13 = gtk_label_new (_("<span foreground=\"red\" ><b>Saisir CIN !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 120, 120);
  gtk_widget_set_size_request (label13, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label3 = gtk_label_new (_("TEL : "));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 320, 232);
  gtk_widget_set_size_request (label3, 104, 48);

  sexeaz = gtk_label_new (_("sexe:"));
  gtk_widget_show (sexeaz);
  gtk_fixed_put (GTK_FIXED (fixed3), sexeaz, 64, 320);
  gtk_widget_set_size_request (sexeaz, 57, 17);

  label8 = gtk_label_new (_("<span foreground=\"red\" ><b>Saisir Prenom !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 384, 184);
  gtk_widget_set_size_request (label8, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  comboboxaz = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxaz);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxaz, 144, 312);
  gtk_widget_set_size_request (comboboxaz, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxaz), _("HOMME"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxaz), _("FEMME"));

  label11 = gtk_label_new (_("<span foreground=\"black\" ><b>Ajouter Etudiant:</b></span>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 376, 24);
  gtk_widget_set_size_request (label11, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed3), button3, 280, 560);
  gtk_widget_set_size_request (button3, 128, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  label35 = gtk_label_new (_("<span foreground=\"green\" ><b>Etudiant ajout\303\251 avec succes !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label35, 232, 608);
  gtk_widget_set_size_request (label35, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  label34 = gtk_label_new (_("<span foreground=\"red\" ><b> Etudiant existant !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label34, 232, 632);
  gtk_widget_set_size_request (label34, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label10 = gtk_label_new (_("<span foreground=\"red\" ><b>Saisir NumTEL !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 384, 256);
  gtk_widget_set_size_request (label10, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label235 = gtk_label_new (_("Etudiant(nouveau/ancien)au foyer:"));
  gtk_widget_show (label235);
  gtk_fixed_put (GTK_FIXED (fixed3), label235, 72, 416);
  gtk_widget_set_size_request (label235, 256, 40);

  button14 = gtk_button_new_with_mnemonic (_("***************INFORMATIONS SUPPLEMENTAIRES*************"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed3), button14, 200, 368);
  gtk_widget_set_size_request (button14, 464, 37);

  labelsexe = gtk_label_new (_("<span foreground=\"red\" ><b>Choisir sexe !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), labelsexe, 160, 344);
  gtk_widget_set_size_request (labelsexe, 128, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelsexe), TRUE);

  label9 = gtk_label_new (_("<span foreground=\"red\" ><b>Saisir Adresse !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 120, 248);
  gtk_widget_set_size_request (label9, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label7 = gtk_label_new (_("<span foreground=\"red\" ><b>Saisir Nom !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 120, 176);
  gtk_widget_set_size_request (label7, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label236 = gtk_label_new (_("Etablissement:"));
  gtk_widget_show (label236);
  gtk_fixed_put (GTK_FIXED (fixed3), label236, 176, 488);
  gtk_widget_set_size_request (label236, 150, 17);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("ancien"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2, 512, 448);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("nouveau"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1, 392, 448);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  OkAZ = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (OkAZ);
  gtk_fixed_put (GTK_FIXED (fixed3), OkAZ, 616, 472);
  gtk_widget_set_size_request (OkAZ, 74, 29);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("ESB"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 512, 488);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("ESE"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 392, 488);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  label234 = gtk_label_new ("");
  gtk_widget_show (label234);
  gtk_fixed_put (GTK_FIXED (fixed3), label234, 192, 408);
  gtk_widget_set_size_request (label234, 360, 120);

  label15 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label15);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 184, 176);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 184, 232);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 184, 344);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9, 184, 288);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label17 = gtk_label_new (_("Adresse : "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 88, 280);
  gtk_widget_set_size_request (label17, 104, 48);

  label18 = gtk_label_new (_("Prenom : "));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 88, 224);
  gtk_widget_set_size_request (label18, 104, 48);

  label19 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 88, 168);
  gtk_widget_set_size_request (label19, 104, 48);

  label16 = gtk_label_new (_("TEL : "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 88, 336);
  gtk_widget_set_size_request (label16, 104, 48);

  label36 = gtk_label_new (_("<span foreground=\"black\" ><b>Modifier l'etudiant de CIN :</b></span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 40, 40);
  gtk_widget_set_size_request (label36, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label20 = gtk_label_new ("");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 248, 48);
  gtk_widget_set_size_request (label20, 56, 48);

  button4 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 168, 432);
  gtk_widget_set_size_request (button4, 128, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox4), label21, FALSE, FALSE, 0);

  image16 = create_pixmap (gestion, "foyer.jpeg");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed4), image16, 424, 136);
  gtk_widget_set_size_request (image16, 352, 288);

  label37 = gtk_label_new (_("<span foreground=\"green\" ><b>Etudiant Modifi\303\251 avec succes </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 312, 432);
  gtk_widget_set_size_request (label37, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label239 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label239);
  gtk_fixed_put (GTK_FIXED (fixed4), label239, 80, 392);
  gtk_widget_set_size_request (label239, 64, 32);

  entrySexe = gtk_entry_new ();
  gtk_widget_show (entrySexe);
  gtk_fixed_put (GTK_FIXED (fixed4), entrySexe, 176, 392);
  gtk_widget_set_size_request (entrySexe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySexe), 8226);

  labelSexe = gtk_label_new ("");
  gtk_widget_show (labelSexe);
  gtk_fixed_put (GTK_FIXED (fixed4), labelSexe, 352, 400);
  gtk_widget_set_size_request (labelSexe, 57, 17);

  label22 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label22);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label22);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow1, 0, 64);
  gtk_widget_set_size_request (scrolledwindow1, 656, 472);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 300, 200);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed5), button5, 192, 552);
  gtk_widget_set_size_request (button5, 128, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);

  label23 = gtk_label_new (_("<span foreground=\"red\" ><b>Selectionner un etudiant !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 344, 552);
  gtk_widget_set_size_request (label23, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label25 = gtk_label_new (_("Afficher&Supprimer"));
  gtk_widget_show (label25);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label25);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow2, 8, 80);
  gtk_widget_set_size_request (scrolledwindow2, 592, 456);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview2);
  gtk_widget_set_size_request (treeview2, 592, 456);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 688, 152);
  gtk_widget_set_size_request (entry10, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label27 = gtk_label_new ("");
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 728, 312);
  gtk_widget_set_size_request (label27, 48, 56);

  label28 = gtk_label_new (_("<span foreground=\"red\" ><b>Saisir Nom !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 680, 176);
  gtk_widget_set_size_request (label28, 216, 64);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed6), button6, 856, 152);
  gtk_widget_set_size_request (button6, 40, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox6), label30, FALSE, FALSE, 0);

  label29 = gtk_label_new (_("Nom : "));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 600, 144);
  gtk_widget_set_size_request (label29, 112, 48);

  label26 = gtk_label_new (_("<span foreground=\"blue\" ><b>Resultat(s) obtenu(s)</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 680, 232);
  gtk_widget_set_size_request (label26, 216, 72);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label31 = gtk_label_new (_("Chercher"));
  gtk_widget_show (label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label31);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton1, 752, 232);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label42 = gtk_label_new (_("Nombre de place"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed7), label42, 608, 216);
  gtk_widget_set_size_request (label42, 136, 56);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow3, 0, 88);
  gtk_widget_set_size_request (scrolledwindow3, 584, 384);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeview3);
  gtk_widget_set_size_request (treeview3, 584, 384);

  label44 = gtk_label_new (_("<span foreground=\"red\"><b>Nombre Invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), label44, 800, 200);
  gtk_widget_set_size_request (label44, 184, 88);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed7), button11, 728, 320);
  gtk_widget_set_size_request (button11, 104, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button11), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox11), label46, FALSE, FALSE, 0);

  label45 = gtk_label_new (_("<span foreground=\"green\"><i>Salle reserv\303\251e</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), label45, 656, 368);
  gtk_widget_set_size_request (label45, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  label43 = gtk_label_new (_("<span foreground=\"red\"><b>Selectionner une Salle !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed7), label43, 600, 248);
  gtk_widget_set_size_request (label43, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label38 = gtk_label_new (_("Revision"));
  gtk_widget_show (label38);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label38);

  g_signal_connect ((gpointer) button14quitaz, "clicked",
                    G_CALLBACK (on_button14quitaz_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13azz_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12_azz, "clicked",
                    G_CALLBACK (on_button12_azz_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_Ajouterfoyer_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) OkAZ, "clicked",
                    G_CALLBACK (on_OkAZ_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_Modifierfoyer_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_Supprimerfoye_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_chercherfoyer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_Reserver_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion, gestion, "gestion");
  GLADE_HOOKUP_OBJECT (gestion, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion, button14quitaz, "button14quitaz");
  GLADE_HOOKUP_OBJECT (gestion, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (gestion, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (gestion, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion, label238, "label238");
  GLADE_HOOKUP_OBJECT (gestion, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gestion, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (gestion, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (gestion, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (gestion, button13, "button13");
  GLADE_HOOKUP_OBJECT (gestion, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestion, button12_azz, "button12_azz");
  GLADE_HOOKUP_OBJECT (gestion, image13, "image13");
  GLADE_HOOKUP_OBJECT (gestion, image17, "image17");
  GLADE_HOOKUP_OBJECT (gestion, label12, "label12");
  GLADE_HOOKUP_OBJECT (gestion, label5, "label5");
  GLADE_HOOKUP_OBJECT (gestion, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion, sexeaz, "sexeaz");
  GLADE_HOOKUP_OBJECT (gestion, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion, comboboxaz, "comboboxaz");
  GLADE_HOOKUP_OBJECT (gestion, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion, button3, "button3");
  GLADE_HOOKUP_OBJECT (gestion, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion, label35, "label35");
  GLADE_HOOKUP_OBJECT (gestion, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion, label235, "label235");
  GLADE_HOOKUP_OBJECT (gestion, button14, "button14");
  GLADE_HOOKUP_OBJECT (gestion, labelsexe, "labelsexe");
  GLADE_HOOKUP_OBJECT (gestion, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion, label236, "label236");
  GLADE_HOOKUP_OBJECT (gestion, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (gestion, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (gestion, OkAZ, "OkAZ");
  GLADE_HOOKUP_OBJECT (gestion, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (gestion, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (gestion, label234, "label234");
  GLADE_HOOKUP_OBJECT (gestion, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (gestion, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (gestion, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (gestion, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (gestion, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion, label36, "label36");
  GLADE_HOOKUP_OBJECT (gestion, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion, image16, "image16");
  GLADE_HOOKUP_OBJECT (gestion, label37, "label37");
  GLADE_HOOKUP_OBJECT (gestion, label239, "label239");
  GLADE_HOOKUP_OBJECT (gestion, entrySexe, "entrySexe");
  GLADE_HOOKUP_OBJECT (gestion, labelSexe, "labelSexe");
  GLADE_HOOKUP_OBJECT (gestion, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestion, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion, button5, "button5");
  GLADE_HOOKUP_OBJECT (gestion, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (gestion, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (gestion, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (gestion, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (gestion, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestion, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion, label26, "label26");
  GLADE_HOOKUP_OBJECT (gestion, label31, "label31");
  GLADE_HOOKUP_OBJECT (gestion, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (gestion, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (gestion, label42, "label42");
  GLADE_HOOKUP_OBJECT (gestion, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (gestion, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (gestion, label44, "label44");
  GLADE_HOOKUP_OBJECT (gestion, button11, "button11");
  GLADE_HOOKUP_OBJECT (gestion, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestion, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestion, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestion, label46, "label46");
  GLADE_HOOKUP_OBJECT (gestion, label45, "label45");
  GLADE_HOOKUP_OBJECT (gestion, label43, "label43");
  GLADE_HOOKUP_OBJECT (gestion, label38, "label38");

  return gestion;
}

GtkWidget*
create_nb (void)
{
  GtkWidget *nb;
  GtkWidget *fixed8;
  GtkWidget *entrynb;
  GtkWidget *buttonnb;
  GtkObject *spinbuttonnb_adj;
  GtkWidget *spinbuttonnb;

  nb = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (nb), _("window1"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (nb), fixed8);

  entrynb = gtk_entry_new ();
  gtk_widget_show (entrynb);
  gtk_fixed_put (GTK_FIXED (fixed8), entrynb, 80, 112);
  gtk_widget_set_size_request (entrynb, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynb), 8226);

  buttonnb = gtk_button_new_with_mnemonic (_("Nombre detud par niv"));
  gtk_widget_show (buttonnb);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonnb, 144, 200);
  gtk_widget_set_size_request (buttonnb, 200, 36);

  spinbuttonnb_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonnb = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonnb_adj), 1, 0);
  gtk_widget_show (spinbuttonnb);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbuttonnb, 256, 112);
  gtk_widget_set_size_request (spinbuttonnb, 60, 27);

  g_signal_connect ((gpointer) buttonnb, "clicked",
                    G_CALLBACK (on_buttonnb_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nb, nb, "nb");
  GLADE_HOOKUP_OBJECT (nb, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (nb, entrynb, "entrynb");
  GLADE_HOOKUP_OBJECT (nb, buttonnb, "buttonnb");
  GLADE_HOOKUP_OBJECT (nb, spinbuttonnb, "spinbuttonnb");

  return nb;
}

